### ISSUE TITLE
How to debug syslog-ng

### ISSUE THREAD

**Issue by lbudai** [balabit/syslog-ng-gitbook#26]
eg.: using heaptracker, etc...

**Comment by ihrwein** [comment]
The following things should be included:
1. preparation
   - [ ] creating debug builds
   - [ ] installing under custom location
2. finding bugs
   - [ ] running in gdb
   - [ ] core dumps
3. finding memory leaks
   - [ ] using heaptracker
   - [ ] running under valgrind

**Comment by justcallmegreg** [comment]
+1
