### ISSUE TITLE
Gitbook points to wrong source for eventlog

### ISSUE THREAD

**Issue by aneutrals** [balabit/syslog-ng-gitbook#44]
Currently the requirements listed for syslog-ng on chapter2/section_1 link to an unrelated github repo with a similar to name to eventlog, but the two projects are unrelated. We should change the link from http://github.com/eldarion/eventlog to https://my.balabit.com/downloads/eventlog/0.2

**Comment by presidento** [comment]
As I see it has been fixed in the commit 6272cbb5c7ee29d1c547ba5b8f8a97acfed11454.
